Move vendor_lib function

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,21 +1,5 @@
 #!/bin/bash
 
-vendor_lib() {
-    LIBRARY=$1
-    VERSION=$2
-    VENDOR_DIR=$3
-
-    echo "-----> Installing $LIBRARY-$VERSION"
-    LIBRARY_URL="https://bucketeer-9aa8f376-a619-404c-b004-6db0317bcfe8.s3.amazonaws.com/$STACK/$LIBRARY/$LIBRARY-$VERSION.tar.gz"
-
-    mkdir -p $VENDOR_DIR
-    if ! curl "${LIBRARY_URL}" -s | tar zxv -C $VENDOR_DIR &> /dev/null; then
-      echo " !     Requested $LIBRARY Version ($VERSION) is not available for this stack ($STACK)."
-      echo " !     Aborting."
-      exit 1
-    fi
-}
-
 BUILD_DIR=$1
 CACHE_DIR=$2
 ENV_DIR=$3
@@ -51,11 +35,11 @@ vendor_lib "PROJ" "$PROJ_VERSION" "$VENDOR_DIR"
 
 # Add some environment variables that are available to the next buildpacks, to ensure that pip can find the
 # GDAL installation as this is needed to pip install GDAL
-echo "export PATH=\"$BUILD_DIR/.heroku-geo-buildpack/vendor/gdal/bin:\$PATH\"" >> "$BP_DIR/export"
-echo "export LIBRARY_PATH=\"$BUILD_DIR/.heroku-geo-buildpack/vendor/gdal/lib:\$LIBRARY_PATH\"" >> "$BP_DIR/export"
-echo "export LD_LIBRARY_PATH=\"$BUILD_DIR/.heroku-geo-buildpack/vendor/gdal/lib:\$LD_LIBRARY_PATH\"" >> "$BP_DIR/export"
-echo "export CPLUS_INCLUDE_PATH=\"$BUILD_DIR/.heroku-geo-buildpack/vendor/gdal/include:\$CPLUS_INCLUDE_PATH\"" >> "$BP_DIR/export"
-echo "export C_INCLUDE_PATH=\"$BUILD_DIR/.heroku-geo-buildpack/vendor/gdal/include:\$C_INCLUDE_PATH\"" >> "$BP_DIR/export"
+echo "export PATH=\"$BUILD_DIR/.heroku-geo-buildpack/vendor/bin:\$PATH\"" >> "$BP_DIR/export"
+echo "export LIBRARY_PATH=\"$BUILD_DIR/.heroku-geo-buildpack/vendor/lib:\$LIBRARY_PATH\"" >> "$BP_DIR/export"
+echo "export LD_LIBRARY_PATH=\"$BUILD_DIR/.heroku-geo-buildpack/vendor/lib:\$LD_LIBRARY_PATH\"" >> "$BP_DIR/export"
+echo "export CPLUS_INCLUDE_PATH=\"$BUILD_DIR/.heroku-geo-buildpack/vendor/include:\$CPLUS_INCLUDE_PATH\"" >> "$BP_DIR/export"
+echo "export C_INCLUDE_PATH=\"$BUILD_DIR/.heroku-geo-buildpack/vendor/include:\$C_INCLUDE_PATH\"" >> "$BP_DIR/export"
 
 
 PROFILE_PATH="$BUILD_DIR/.profile.d/heroku-geo-buildpack.sh"
@@ -67,3 +51,20 @@ echo 'export GEOS_LIBRARY_PATH="$HOME/.heroku-geo-buildpack/vendor/lib/libgeos_c
 echo 'export PROJ4_LIBRARY_PATH="$HOME/.heroku-geo-buildpack/vendor/lib/libproj.so"' >> $PROFILE_PATH
 echo 'export PATH="$HOME/.heroku-geo-buildpack/vendor/bin:$PATH"' >> $PROFILE_PATH
 echo 'export LD_LIBRARY_PATH="$HOME/.heroku-geo-buildpack/vendor/lib:$LD_LIBRARY_PATH"' >> $PROFILE_PATH
+
+
+vendor_lib() {
+    LIBRARY=$1
+    VERSION=$2
+    VENDOR_DIR=$3
+
+    echo "-----> Installing $LIBRARY-$VERSION"
+    LIBRARY_URL="https://bucketeer-9aa8f376-a619-404c-b004-6db0317bcfe8.s3.amazonaws.com/$STACK/$LIBRARY/$LIBRARY-$VERSION.tar.gz"
+
+    mkdir -p $VENDOR_DIR
+    if ! curl "${LIBRARY_URL}" -s | tar zxv -C $VENDOR_DIR &> /dev/null; then
+      echo " !     Requested $LIBRARY Version ($VERSION) is not available for this stack ($STACK)."
+      echo " !     Aborting."
+      exit 1
+    fi
+}
